---
channel: edge
addons:
  redreactor:
    repository: mreditor97/addon-redreactor
    target: redreactor
    image: ghcr.io/mreditor97/redreactor/{arch}
  dns-godaddy:
    repository: mreditor97/addon-ddns-godaddy
    target: ddns-godaddy
    image: ghcr.io/mreditor97/ddns-godaddy/{arch}
