name: Red Reactor Battery Monitor
description: Red Reactor Battery Monitoring service
version: 0.1.1
slug: redreactor
url: https://github.com/mreditor97/addon-redreactor
startup: services
arch:
- aarch64
- armhf
- armv7
init: false
privileged:
- SYS_ADMIN
devices:
- /dev/i2c-1
hassio_api: true
hassio_role: manager
services:
- mqtt:want
options:
  mqtt:
    broker: core-mosquitto
    port: 1883
    user: redreactor
    password: redreactor
  hostname:
    name: redreactor-pi
    pretty: Raspberry Pi
  homeassistant:
    discovery_interval: 120
    expire_after: 120
  system:
    shutdown: ha host shutdown
    restart: ha host restart
  logging:
    console: INFO
    file: WARNING
schema:
  mqtt:
    broker: str
    port: port
    user: str
    password: password
  hostname:
    name: str
    pretty: str
  homeassistant:
    discovery_interval: int
    expire_after: int
  system:
    shutdown: str
    restart: str
  logging:
    console: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
    file: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
image: ghcr.io/mreditor97/redreactor/{arch}
