name: GoDaddy Dynamic DNS Updater
description: GoDaddy Dynamic DNS updating service with Let's Encrypt support
version: b5d943e
slug: ddns-godaddy
url: https://github.com/mreditor97/addon-ddns-godaddy
startup: services
arch:
- aarch64
- armhf
- armv7
- amd64
- i386
init: false
map:
- ssl:rw
options:
  domain: my-godaddy-domain.com
  hostname: my-hostname
  key: GoDaddy API Key
  secret: GoDaddy API Secret
  ttl: 600
  scan_interval: 300
  lets_encrypt:
    accept_terms: false
    certfile: fullchain.pem
    keyfile: privkey.pem
    renewal_period: 5184000
    dns_delay: 30
schema:
  domain: str
  hostname: str
  key: str
  secret: str
  ttl: int
  scan_interval: int
  lets_encrypt:
    accept_terms: bool
    certfile: str
    keyfile: str
    renewal_period: int
    dns_delay: int
  ipv4: str?
  ipv6: str?
image: ghcr.io/mreditor97/ddns-godaddy/{arch}
